### ISSUE TITLE
drobne uwagi

### ISSUE THREAD

**Issue by Jonasz-D** [MrGegi/Bot---Syntax-Conquerors#67]
Wydaje mi się, że kod działa poprawnie. Znalazłem tylko kilka kosmetycznych usterek
Sugeruję poniższych usterek nie poprawiać, bo w przeddzień oddania projektu moglibyśmy niepotrzebnie coś zepsuć. 
Wrzucam te uwagi tylko po to, aby w trakcie jutrzejszej prezentacji projektu tych usterek nie wywołać:
- numeru z prefiksem +48 lub 048 nie da się wpisać ze względu na ograniczenie do 9 cyfr;
- gdy kontakt posiada numer tel, to po zastosowaniu funkcji add phone, numer jest podmieniany
- gdy kontakt posiada email, to po zastosowaniu funkcji add email, email jest podmieniany
- gdy do kontaktu damy zbyt dużą ilość znaków (np w email), to tabelka się rozjedzie
- brak możliwości zmiany daty urodzin (w przypadku wpisania błędnej)
- gdy do notatki damy zbyt dużą ilość znaków, to tabelka się rozjedzie

**Comment by Vincenty82** [comment]
@Jonasz-D @MrGegi #72 is a congregated patch that fixes issues and adds some of the missing features.
- add phone fixed
- add email fixed
- add birthday now allows editing
- added future date set guardrail to birthday
- other minor fixes

Rest of the bugs will need to be pushed for next sprint. Closing as completed.
